project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4000

website:
  title: "WGBS Genome Coverage"
  description: "Coverage from WGBS experiments"
  page-footer:
    left: "Copyright 2024, Jacob Morrison"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: website/artifacts.qmd
        text: "Artifacts"
    right:
      - icon: github
        href: https://github.com/jamorrison/GVSU-CIS641-PackingTheBits
  sidebar:
    - title: "Home"
      style: "docked"
      background: "#E3E3E3"
      search: true
      contents:
        - index.qmd
        - href: website/artifacts.qmd
          text: "Artifacts"
    - title: "Artifacts"
      style: "docked"
      background: "#E3E3E3"
      search: true
      contents:
        - artifacts.qmd
        - href: artifacts/system_request.md
          text: System Request
        - href: website/diagrams.qmd
          text: Diagrams (Use Case, Activity)

format:
  html:
    theme: yeti
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"
    number-sections: false



