project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4000

website:
  title: "WGBS Genome Coverage"
  description: "Coverage from WGBS experiments"
  page-footer:
    left: "Copyright 2024, Jacob Morrison"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Artifacts"
        href: website/artifacts.qmd
      - text: "Documents"
        href: website/docs.qmd
      - text: "Meetings"
        href: website/meetings.qmd
    right:
      - icon: github
        href: https://github.com/jamorrison/GVSU-CIS641-PackingTheBits
  sidebar:
    - title: "Artifacts"
      style: "docked"
      background: "#E3E3E3"
      contents:
        - website/artifacts.qmd
        - text: "---"
        - text: "System Request"
          href: artifacts/system_request.md
        - text: "Diagrams (Use Case, Activity)"
          href: website/diagrams.qmd
    - title: "Documents"
      style: "docked"
      background: "#E3E3E3"
      contents:
        - website/docs.qmd
        - text: "---"
        - text: "Project Proposal"
          href: docs/project-proposal.md
        - text: "Software Requirements Specification"
          href: docs/software_requirements_specification.md
    - title: "Meeting Minutes"
      style: "docked"
      background: "#E3E3E3"
      contents:
        - website/meetings.qmd
        - text: "---"
        - text: "2024-09-30"
          href: meetings/GVSU-CIS641-PackingTheBits-2024-09-30.md
        - text: "2024-10-07"
          href: meetings/GVSU-CIS641-PackingTheBits-2024-10-07.md

format:
  html:
    theme: yeti
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"
    number-sections: false



