project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4000

website:
  title: "WGBS Genome Coverage"
  description: "Coverage from WGBS experiments"
  page-footer:
    left: "Copyright 2024, Jacob Morrison"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Artifacts"
        href: website/artifacts.qmd
    right:
      - icon: github
        href: https://github.com/jamorrison/GVSU-CIS641-PackingTheBits
  sidebar:
    - title: "Home"
      style: "docked"
      background: "#E3E3E3"
      contents:
        - index.qmd
        - text: "Artifacts"
          href: website/artifacts.qmd
    - title: "Artifacts"
      style: "docked"
      background: "#E3E3E3"
      contents:
        - website/artifacts.qmd
        - text: "System Request"
          href: artifacts/system_request.md
        - text: "Diagrams (Use Case, Activity)"
          href: website/diagrams.qmd

format:
  html:
    theme: yeti
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"
    number-sections: false



