---
title: "Genomic Coverage from Whole Genome Bisulfite Sequencing Data"
---

# Description

DNA sequencing is a common practice in biomedical research. The sequencing process requires collecting DNA from a
sample (e.g., a tumor biopsy or a healthy tissue nearby), extracting the DNA from the cells, and then fragmenting the
full length DNA strands into smaller chunks. These chunks are then placed on a "sequencer," where the individual bases
are read from the DNA fragments. The output from the sequencer is called a "read" and is then aligned back to a
reference genome (the human reference genome is about three billion bases long) in order to find where the small
fragment (usually around 100-150 bases in length) came from.

One possible analysis that can be done is to find the "coverage" across the entire genome. To do this, you count the
total number of reads that cover each individual loci, or base, in the genome. One example of performing this analysis
is as a part of a quality control pipeline within [BISCUIT](https://github.com/huishenlab/biscuit) to verify a
sequencing experiment consistently covered the entire genome. Currently, the pipeline uses
[bedtools](https://github.com/arq5x/bedtools2) to do this, but it is a slow process. One option for improving the speed
of this process would be to use [mosdepth](https://github.com/brentp/mosdepth), a tool specifically designed for finding
coverages. However, it does not calculate the exact metrics needed in the BISCUIT quality control pipeline.

This project improves upon the existing bedtools implementation by calculating the needed metrics on the fly and
utilizing parallelization during processing. The tool is written in C for plugging in to BISCUIT following its
completion.

# Deliverables

- [Artifacts](website/artifacts.qmd)
  - [System request](artifacts/system_request.md)
  - [Diagrams (use case, activity, etc.)](website/diagrams.qmd)
- [Documents](website/docs.qmd)
  - [Project proposal](docs/project-proposal.md)
  - [Software Requirements Specification](docs/software_requirements_specification.md)
  - [Software Requirements Specification (Final Version)](docs/software_requirements_specification_final.md)
  - [Midterm Presentation](website/midterm_presentation.qmd)
- [Meeting Minutes](website/meetings.qmd)
  - [30 September 2024](meetings/GVSU-CIS641-PackingTheBits-2024-09-30.md)
  - [07 October 2024](meetings/GVSU-CIS641-PackingTheBits-2024-10-07.md)
  - [14 October 2024](meetings/GVSU-CIS641-PackingTheBits-2024-10-14.md)
  - [23 October 2024](meetings/GVSU-CIS641-PackingTheBits-2024-10-23.md)
  - [28 October 2024](meetings/GVSU-CIS641-PackingTheBits-2024-10-28.md)
  - [04 November 2024](meetings/GVSU-CIS641-PackingTheBits-2024-11-04.md)
  - [11 November 2024](meetings/GVSU-CIS641-PackingTheBits-2024-11-11.md)
  - [18 November 2024](meetings/GVSU-CIS641-PackingTheBits-2024-11-18.md)
  - [25 November 2024](meetings/GVSU-CIS641-PackingTheBits-2024-11-25.md)
  - [02 December 2024](meetings/GVSU-CIS641-PackingTheBits-2024-12-02.md)
